In [2]:
import numpy as np
arr2 = np.array([['장하린', '강민승', '강현성'],
                ['임성우', '박준혁', '최우석'],
               ['최성근', '고영승', '장진수']])


In [3]:
arr2_arr = np.array([['채지은'],
                     ['최서희'],
                     ['최지웅']])

arr2 = np.concatenate((arr2, arr2_arr),axis = 1)
print(arr2)
arr2.shape

[['장하린' '강민승' '강현성' '채지은']
 ['임성우' '박준혁' '최우석' '최서희']
 ['최성근' '고영승' '장진수' '최지웅']]


(3, 4)

In [4]:
arr_org = np.array([[1,0,4],
                   [0,2,3]])
arrtrans = np.transpose(arr_org)
arrtrans

array([[1, 0],
       [0, 2],
       [4, 3]])

In [5]:
arr113 = np.arange(3).reshape(1,1,3)
arr113

array([[[0, 1, 2]]])

In [6]:
arr131 = np.arange(3).reshape(1,3,1)
arr131

array([[[0],
        [1],
        [2]]])

In [7]:
arr311 = np.arange(3).reshape(3,1,1)
arr311

array([[[0]],

       [[1]],

       [[2]]])

퍼셉트론

In [11]:
def AND(x1,x2):
    w1,w2,theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    else:
        return 1

print(AND(0,0))
print(AND(0,1))
print(AND(1,0))
print(AND(1,1))

0
0
0
1


In [13]:
import numpy as np
def AND(x):
    w = np.array([0.5, 0.5])
    b = -0.7
    y = np.sum(w*x) + b
    if y <= 0:
        return 0
    elif y > 0:
        return 1

AND(np.array([0,0]))

0

In [14]:
import numpy as np
def AND(x1,x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.7
    y = np.sum(w*x) + b
    if y <= 0:
        return 0
    elif y > 0:
        return 1
    
AND(0,1)

0

In [17]:
def NAND(x1,x2):
    x = np.array([x1,x2])
    w = np.array([-0.5,-0.5]) #(NAND 게이트 이므로 부호 반전)
    b = 0.7
    y = np.sum(w*x) + b
    if y <= 0:
        return 0
    else:
        return 1
    
NAND(0,0)

1

In [18]:
NAND(0,1)

1

In [20]:
def OR(x1,x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.2 #(0.5보다 크면 OR게이트로 작동할 수 없음)
    y = np.sum(w*x) + b
    if y <= 0:
        return 0
    else:
        return 1

print(OR(0,0))
print(OR(0,1))
print(OR(1,0))
print(OR(1,1))


0
1
1
1


In [23]:
def XOR(x1,x2):
    s1 = NAND(x1,x2)
    s2 = OR(x1,x2)
    y = AND(s1,s2)
    return y

print(XOR(0,0))
print(XOR(0,1))
print(XOR(1,0))
print(XOR(1,1))

0
1
1
0


연습문제
(1) 지난 시간까지 실습했던 연습문제를 클래스

In [ ]:
#클래스로 작성
import numpy as np

class Sub_set:
    def __init__(self, arr):
        self.arr = arr
    
    def subset(self):
        odd_list = []
        even_list = []

        for i in range(self.arr.shape[0]):
            for j in range(self.arr.shape[1]):
                for k in range(self.arr.shape[2]):
                    if (i + j + k) % 2 == 0:
                        even_list.append(self.arr[i][j][k])
                    else:
                        odd_list.append(self.arr[i][j][k])

        print("홀수 집합:", odd_list)
        print("\n")
        print("짝수 집합:", even_list)
        
subset_calculator = Sub_set(arr1)


subset_calculator.subset()

In [ ]:
#클래스 구현
import numpy as np

input_name = input("찾을 이름은 : ")

class Find_position:
    def __init__(self,arr,input_name):
        self.arr = arr
        self.input_name = input_name
        self.count = 0
        
    def 배열생성(self,n,s):
        m = 1
        while m != s: #m != s일 때까지 반복
            result = np.random.randint(m,n, size = m) #m~n-1까지 m개만큼 추출
            print(result, m, n)
            m += 1 #m 하나씩 증가
        return result
#arr1.ndim = arr1의 차원 #10, 4
    def find(self):
        ret = self.배열생성(10, self.arr.ndim + 1)
        
        while True:
            for i in range(ret.size): #0~2
                ret[i] = ret[i] % self.arr.shape[i] #각 리스트의 번호들을 arr.shape로 나눈다
            print("=============")  
            print("결과는 :", ret) #ret 리스트의 전체를 프린트한다.
            name = self.arr[ret[0], ret[1], ret[2]] #name = arr1의 ret 리스트의 각 번호들로 지정한다
            print("이름은 : ", name)
            self.count += 1
            print("횟수는 : ", self.count, "번째")
            print("\n")
        
            if name == self.input_name:
                print("이름의 위치는 : ", ret)
                print("해당하는 이름이 위치한 리스트 번호까지의 리스트들은 :")
            
                for fi in range(ret[0] + 1): #fi = 0~0
                    for se in range(ret[1] + 1): #se = 0~1
                        for th in range(ret[2] + 1): ##th = 0~2
                            print("[",fi, se, th,"]", self.arr[fi][se][th])
                break
                                  
                            
                #이름의 위치가 0 1 2이므로 0~0, 0~1, 0~2까지의 모든 수를 다 프린트
            ret = self.배열생성(10, self.arr.ndim+1) #이재웅이 아닌 이름이 나오면 ret을 새로 생성하여 새로운 인덱스를 얻을 수 있다.

find_name = Find_position(arr1, input_name)
find_name.find()

In [94]:
#최종버전
import numpy as np
from numpy.random import randn
import random

class set:
    
    def __init__(self,i):
        self.i = 3
    def set_pro(self):
        
        self.i = 3
        j = random.randrange(1,6)
        m = random.randrange(3,6)
        print(self.i, j, m)
        print("\n")

        arr1_num = np.array(randn(self.i, j, m) * 10, dtype=np.int64)
        print(arr1_num)
        print("==============")
        print("\n")

        arr1_pro = arr1_num[0, 0, :3].reshape(1, 1, 3)

        print("(1,1,3)의 배열은 :", arr1_pro)
        print("\n")

        arr1_transpose = arr1_pro.transpose(2, 1, 0)
        print("(3,1,1)로 변경한 배열은 :\n", arr1_transpose)
        print("\n")
        arr1_multi = arr1_num * arr1_transpose

        print("곱한 배열은 :\n", arr1_multi)
        print("\n")
        arr_ex_line = np.concatenate((arr1_num, np.array(randn(1, j, m) * 10, dtype=np.int64)), axis=0)
        print("행의 확장은: \n", arr_ex_line)
        print("\n")

        # list = []
        # for _ in range(i+1):
        #     a = np.array(randn(1, 1, 1) * 10, dtype=np.int64)
        #     list.append(a)
        # print(list)
        print("원본 배열:\n", arr1_num)
        print("\n")
        arr_ex_col = np.concatenate((arr1_num, np.array(randn(self.i, j, 1) * 10, dtype=np.int64)), axis=2)
        print("열의 확장은: \n", arr_ex_col)

set_check = set(3)
set_check.set_pro()

3 2 5


[[[  0   1  -3   5   7]
  [-18   7  11  -1  -9]]

 [[ -4  -3   0 -10  -3]
  [ -8  -4   9 -13  -3]]

 [[ 11   8  -1  16   0]
  [  7   2  12  13   4]]]


(1,1,3)의 배열은 : [[[ 0  1 -3]]]


(3,1,1)로 변경한 배열은 :
 [[[ 0]]

 [[ 1]]

 [[-3]]]


곱한 배열은 :
 [[[  0   0   0   0   0]
  [  0   0   0   0   0]]

 [[ -4  -3   0 -10  -3]
  [ -8  -4   9 -13  -3]]

 [[-33 -24   3 -48   0]
  [-21  -6 -36 -39 -12]]]


행의 확장은: 
 [[[  0   1  -3   5   7]
  [-18   7  11  -1  -9]]

 [[ -4  -3   0 -10  -3]
  [ -8  -4   9 -13  -3]]

 [[ 11   8  -1  16   0]
  [  7   2  12  13   4]]

 [[ 14 -24  -1   5 -12]
  [ -1  -5   0   4  25]]]


원본 배열:
 [[[  0   1  -3   5   7]
  [-18   7  11  -1  -9]]

 [[ -4  -3   0 -10  -3]
  [ -8  -4   9 -13  -3]]

 [[ 11   8  -1  16   0]
  [  7   2  12  13   4]]]


열의 확장은: 
 [[[  0   1  -3   5   7 -14]
  [-18   7  11  -1  -9 -10]]

 [[ -4  -3   0 -10  -3  -3]
  [ -8  -4   9 -13  -3  -3]]

 [[ 11   8  -1  16   0   1]
  [  7   2  12  13   4  16]]]


합쳐보기

In [95]:
import numpy as np
from numpy.random import randn
import random


class Sub_set:
    def __init__(self, arr):
        self.arr = arr
    
    def subset(self):
        odd_list = []
        even_list = []

        for i in range(self.arr.shape[0]):
            for j in range(self.arr.shape[1]):
                for k in range(self.arr.shape[2]):
                    if (i + j + k) % 2 == 0:
                        even_list.append(self.arr[i][j][k])
                    else:
                        odd_list.append(self.arr[i][j][k])

        print("홀수 집합:", odd_list)
        print("\n")
        print("짝수 집합:", even_list)


input_name = input("찾을 이름은 : ")

class Find_position:
    def __init__(self,arr,input_name):
        self.arr = arr
        self.input_name = input_name
        self.count = 0
        
    def 배열생성(self,n,s):
        m = 1
        while m != s: #m != s일 때까지 반복
            result = np.random.randint(m,n, size = m) #m~n-1까지 m개만큼 추출
            print(result, m, n)
            m += 1 #m 하나씩 증가
        return result
#arr1.ndim = arr1의 차원 #10, 4
    def find(self):
        ret = self.배열생성(10, self.arr.ndim + 1)
        
        while True:
            for i in range(ret.size): #0~2
                ret[i] = ret[i] % self.arr.shape[i] #각 리스트의 번호들을 arr.shape로 나눈다
            print("=============")  
            print("결과는 :", ret) #ret 리스트의 전체를 프린트한다.
            name = self.arr[ret[0], ret[1], ret[2]] #name = arr1의 ret 리스트의 각 번호들로 지정한다
            print("이름은 : ", name)
            self.count += 1
            print("횟수는 : ", self.count, "번째")
            print("\n")
        
            if name == self.input_name:
                print("이름의 위치는 : ", ret)
                print("해당하는 이름이 위치한 리스트 번호까지의 리스트들은 :")
            
                for fi in range(ret[0] + 1): #fi = 0~0
                    for se in range(ret[1] + 1): #se = 0~1
                        for th in range(ret[2] + 1): ##th = 0~2
                            print("[",fi, se, th,"]", self.arr[fi][se][th])
                break
                                  
                            
                #이름의 위치가 0 1 2이므로 0~0, 0~1, 0~2까지의 모든 수를 다 프린트
            ret = self.배열생성(10, self.arr.ndim+1) #이재웅이 아닌 이름이 나오면 ret을 새로 생성하여 새로운 인덱스를 얻을 수 있다.

class set:
    
    def __init__(self,i):
        self.i = 3
    def set_pro(self):
        
        self.i = 3
        j = random.randrange(1,6)
        m = random.randrange(3,6)
        print(self.i, j, m)
        print("\n")

        arr1_num = np.array(randn(self.i, j, m) * 10, dtype=np.int64)
        print(arr1_num)
        print("==============")
        print("\n")

        arr1_pro = arr1_num[0, 0, :3].reshape(1, 1, 3)

        print("(1,1,3)의 배열은 :", arr1_pro)
        print("\n")

        arr1_transpose = arr1_pro.transpose(2, 1, 0)
        print("(3,1,1)로 변경한 배열은 :\n", arr1_transpose)
        print("\n")
        arr1_multi = arr1_num * arr1_transpose

        print("곱한 배열은 :\n", arr1_multi)
        print("\n")
        arr_ex_line = np.concatenate((arr1_num, np.array(randn(1, j, m) * 10, dtype=np.int64)), axis=0)
        print("행의 확장은: \n", arr_ex_line)
        print("\n")

        # list = []
        # for _ in range(i+1):
        #     a = np.array(randn(1, 1, 1) * 10, dtype=np.int64)
        #     list.append(a)
        # print(list)
        print("원본 배열:\n", arr1_num)
        print("\n")
        arr_ex_col = np.concatenate((arr1_num, np.array(randn(self.i, j, 1) * 10, dtype=np.int64)), axis=2)
        print("열의 확장은: \n", arr_ex_col)

        
arr1 = np.array([[["ㄱㄱㄱ", "ㄴㄴㄴ", "ㄷㄷㄷ"],
                 ["ㄹㄹㄹ", "ㅁㅁㅁ", "ㅂㅂㅂ"]],
                 
                 [["ㅅㅅㅅ", "ㅇㅇㅇ", "이재웅"], 
                  ["ㅊㅊㅊ", "ㅋㅋㅋ", "ㅍㅍㅍ"]],
                 
                  [["가가가", "나나나", "다다다"],
                   ["라라라", "마마마", "바바바"]],
                 
                 [["사사사", "아아아", "자자자"],
                 ["차차차","카카카","파파파"]],
                 
                [["이지호", "이현준", "임채린"],
                ["채지은", "최서희", "최지웅"]]])

#출력
print("1번 문제")
subset_calculator = Sub_set(arr1)
subset_calculator.subset()
print("\n")
print("2번 문제")
find_name = Find_position(arr1, input_name)
find_name.find()
print("\n")
print("3번 문제")
set_check = set(3)
set_check.set_pro()

찾을 이름은 : 이재웅
1번 문제
홀수 집합: ['ㄴㄴㄴ', 'ㄹㄹㄹ', 'ㅂㅂㅂ', 'ㅅㅅㅅ', '이재웅', 'ㅋㅋㅋ', '나나나', '라라라', '바바바', '사사사', '자자자', '카카카', '이현준', '채지은', '최지웅']


짝수 집합: ['ㄱㄱㄱ', 'ㄷㄷㄷ', 'ㅁㅁㅁ', 'ㅇㅇㅇ', 'ㅊㅊㅊ', 'ㅍㅍㅍ', '가가가', '다다다', '마마마', '아아아', '차차차', '파파파', '이지호', '임채린', '최서희']


2번 문제
[9] 1 10
[6 7] 2 10
[8 5 9] 3 10
결과는 : [3 1 0]
이름은 :  차차차
횟수는 :  1 번째


[1] 1 10
[8 7] 2 10
[3 6 3] 3 10
결과는 : [3 0 0]
이름은 :  사사사
횟수는 :  2 번째


[1] 1 10
[7 3] 2 10
[9 7 6] 3 10
결과는 : [4 1 0]
이름은 :  채지은
횟수는 :  3 번째


[1] 1 10
[7 5] 2 10
[8 4 7] 3 10
결과는 : [3 0 1]
이름은 :  아아아
횟수는 :  4 번째


[3] 1 10
[5 5] 2 10
[8 3 8] 3 10
결과는 : [3 1 2]
이름은 :  파파파
횟수는 :  5 번째


[9] 1 10
[9 8] 2 10
[4 5 3] 3 10
결과는 : [4 1 0]
이름은 :  채지은
횟수는 :  6 번째


[2] 1 10
[4 8] 2 10
[8 5 6] 3 10
결과는 : [3 1 0]
이름은 :  차차차
횟수는 :  7 번째


[6] 1 10
[4 2] 2 10
[4 4 6] 3 10
결과는 : [4 0 0]
이름은 :  이지호
횟수는 :  8 번째


[9] 1 10
[5 4] 2 10
[3 8 5] 3 10
결과는 : [3 0 2]
이름은 :  자자자
횟수는 :  9 번째


[8] 1 10
[9 2] 2 10
[4 5 3] 3 10
결과는 : [4 1 0]
이름은 :  채지은
횟수는 :  10 번째


[1] 1 10
[4 9] 2 10
[7 8

어떤 임의의 3차원 이상의 배열에 대해 난수로 범위지정이 된 슬라이싱을 구하세요. 
또한 해당 원배열의 전치행렬을 구해보세요(전치행렬의 형태는 n차원개로 나오겠지만, 하나만 제시)
그리고 특정 난수로 해당 원배열을 reshape해보세요

난수가 범위를 벗어나면 나머지

In [96]:
import numpy as np
from numpy.random import randn
import random
#시간 남으면 n차원까지
class arr_pro:
    def __init__(self,i):
        self.i = i
    def make(self):
        self.i = random.randrange(1,6)
        j = random.randrange(1,6)
        m = random.randrange(1,6)
        print(i,j,m)
        print("\n")
        arr = np.array(randn(self.i,j,m) * 10, dtype = np.int64)
        print("랜덤한 배열은 \n", arr)
        print("\n")

        ra_i = random.randrange(1,self.i+1)
        ra_j = random.randrange(1,j+1)
        ra_m = random.randrange(1,m+1)
        print(ra_i+1,ra_j+1,ra_m+1)
        print("\n")
        #나온 수의 리스트 번호까지 출력

        ra_arr = arr[:ra_i,:ra_j,:ra_m]
        #어차피 슬라이싱할 땐 0~ra_i-1, 0~ra_j-1, 0~ra_m-1
        print("랜덤으로 슬라이싱한 배열: \n", ra_arr)
        print("\n")

        arr_trans = np.transpose(arr)

        print("전치행렬은 :\n", arr_trans)
        print("\n")
        sum_num = self.i * j * m

        print("배열의 수는: ", sum_num)
        print("\n")

        while True:
            ran_num1 = random.randrange(1, 5)  # 1부터 4까지의 임의의 수를 생성합니다.

            result = sum_num % ran_num1

            if result == 0:
                break
            else:
                print("다시 시도합니다.")


        ran_num2 = sum_num // ran_num1
        print(ran_num1,ran_num2)

        reshape_arr = arr.reshape(ran_num1,ran_num2)

        print("reshape arr : \n", reshape_arr)

make_arr = arr_pro()

arr_pro.make()
# arr.reshape(ran_num1,ran_num2)
#sum_num보다 작거나 같은 수

TypeError: __init__() missing 1 required positional argument: 'i'

In [97]:
import numpy as np
from numpy.random import randn
import random
#시간 남으면 n차원까지

i = random.randrange(1,6)
j = random.randrange(1,6)
m = random.randrange(1,6)
print(i,j,m)
print("\n")
arr = np.array(randn(i,j,m) * 10, dtype = np.int64)
print("랜덤한 배열은 \n", arr)
print("\n")

ra_i = random.randrange(1,i+1)
ra_j = random.randrange(1,j+1)
ra_m = random.randrange(1,m+1)
print(ra_i+1,ra_j+1,ra_m+1)
print("\n")
#나온 수의 리스트 번호까지 출력

ra_arr = arr[:ra_i,:ra_j,:ra_m]
#어차피 슬라이싱할 땐 0~ra_i-1, 0~ra_j-1, 0~ra_m-1
print("랜덤으로 슬라이싱한 배열: \n", ra_arr)
print("\n")

arr_trans = np.transpose(arr)

print("전치행렬은 :\n", arr_trans)
print("\n")
sum_num = i * j * m

print("배열의 수는: ", sum_num)
print("\n")

while True:
    ran_num1 = random.randrange(1, 5)  # 1부터 4까지의 임의의 수를 생성합니다.

    result = sum_num % ran_num1

    if result == 0:
        break
    else:
        print("다시 시도합니다.")


ran_num2 = sum_num // ran_num1
print(ran_num1,ran_num2)

reshape_arr = arr.reshape(ran_num1,ran_num2)

print("reshape arr : \n", reshape_arr)

# arr.reshape(ran_num1,ran_num2)
#sum_num보다 작거나 같은 수

2 1 5


랜덤한 배열은 
 [[[  0  -2   9 -14   3]]

 [[ 13  -2   7   1   1]]]


2 2 5


랜덤으로 슬라이싱한 배열: 
 [[[  0  -2   9 -14]]]


전치행렬은 :
 [[[  0  13]]

 [[ -2  -2]]

 [[  9   7]]

 [[-14   1]]

 [[  3   1]]]


배열의 수는:  10


다시 시도합니다.
다시 시도합니다.
2 5
reshape arr : 
 [[  0  -2   9 -14   3]
 [ 13  -2   7   1   1]]


In [97]:
def divisor(num):
    result = []
    for i in range(1, int(num ** (1/2))+1):
        if num % i == 0:
            result.append(i)
    return result

divisor(125)

[]


In [30]:
sum_num = 200
ran_a = random.randrange(1, sum_num)  # 초기값 설정

while sum_num % ran_a != 0:  # ran_a로 나눈 나머지가 0이 아닌 경우 반복
    ran_a = random.randrange(1, sum_num)

print("ran_a:", ran_a)


ran_a: 20


In [37]:
import random

sum_num = 200

ran_a = random.randrange(1, sum_num)
while sum_num % ran_a != 0:
    ran_a = random.randrange(1, sum_num)
print("ran_a:", ran_a)

ran_a = random.randrange(1, sum_num)
while sum_num % ran_a != 0:
    ran_a = random.randrange(1, sum_num)
print("ran_a:", ran_a)

ran_a: 2
ran_a: 20
ran_a: 2


In [48]:
import random

sum_num = 200


ran_a = random.randrange(1, sum_num)
while sum_num % ran_a != 0:
    ran_a = random.randrange(1, sum_num)
print("ran_a:", ran_a)

    # ran_a로 나눈 값을 한 번 더 나누어서 출력

ran_b = random.randrange(1, ran_a)
while ran_a % ran_b != 0:
    ran_b = random.randrange(1, ran_a)
print("ran_b:", ran_b)


ran_a: 4
ran_b: 1
